--------------------------------------------------------
-- Archivo creado  - viernes-mayo-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CADENA
--------------------------------------------------------

  CREATE TABLE "VS2DAWTESTJPA2"."CADENA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"WEB" VARCHAR2(200 BYTE), 
	"IMAGEN" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GRUPOS
--------------------------------------------------------

  CREATE TABLE "VS2DAWTESTJPA2"."GRUPOS" 
   (	"IDGRUPO" VARCHAR2(30 BYTE), 
	"IDUSUARIO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OFERTAS
--------------------------------------------------------

  CREATE TABLE "VS2DAWTESTJPA2"."OFERTAS" 
   (	"ID" NUMBER, 
	"CADENA" NUMBER, 
	"DESCRIPCION" VARCHAR2(1000 BYTE), 
	"IMAGEN" VARCHAR2(50 BYTE), 
	"WEB" VARCHAR2(200 BYTE), 
	"CODIGO" VARCHAR2(30 BYTE), 
	"USUARIO" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "VS2DAWTESTJPA2"."USUARIOS" 
   (	"USUARIO" VARCHAR2(30 BYTE), 
	"CLAVE" VARCHAR2(32 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VS2DAWTESTJPA2"."TABLE1_PK" ON "VS2DAWTESTJPA2"."CADENA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_GRUPOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "VS2DAWTESTJPA2"."PK_GRUPOS" ON "VS2DAWTESTJPA2"."GRUPOS" ("IDGRUPO", "IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OFERTAS_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "VS2DAWTESTJPA2"."OFERTAS_PK1" ON "VS2DAWTESTJPA2"."OFERTAS" ("ID", "CADENA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "VS2DAWTESTJPA2"."PK_USUARIOS" ON "VS2DAWTESTJPA2"."USUARIOS" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CADENA
--------------------------------------------------------

  ALTER TABLE "VS2DAWTESTJPA2"."CADENA" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "VS2DAWTESTJPA2"."CADENA" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "VS2DAWTESTJPA2"."CADENA" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRUPOS
--------------------------------------------------------

  ALTER TABLE "VS2DAWTESTJPA2"."GRUPOS" ADD CONSTRAINT "PK_GRUPOS" PRIMARY KEY ("IDGRUPO", "IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OFERTAS
--------------------------------------------------------

  ALTER TABLE "VS2DAWTESTJPA2"."OFERTAS" ADD CONSTRAINT "OFERTAS_PK" PRIMARY KEY ("ID", "CADENA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "VS2DAWTESTJPA2"."OFERTAS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "VS2DAWTESTJPA2"."OFERTAS" MODIFY ("CADENA" NOT NULL ENABLE);
 
  ALTER TABLE "VS2DAWTESTJPA2"."OFERTAS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
 
  ALTER TABLE "VS2DAWTESTJPA2"."OFERTAS" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "VS2DAWTESTJPA2"."USUARIOS" ADD CONSTRAINT "PK_USUARIOS" PRIMARY KEY ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
